repos:
- repo: git://github.com/pre-commit/pre-commit-hooks
  rev: v2.2.1
  hooks:
  # tidy up extra whitespace at end of files
  - id: trailing-whitespace
  # ensure consistent newline endings for files (\n only)
  - id: end-of-file-fixer
  # fix newlines in general to prevent pesky windows users writing CRLF
  - id: mixed-line-ending
    args:
      - --fix=lf
  # do not allow pdb/breakpoint statements to be checked in
  - id: debug-statements
  # run flake8 for linting/ensuring pep8
  - id: flake8
    args:
      - --max-line-length=120
      # Make flake8 ignore black's opinions
      # E126 - continuation line over-indented for hanging indent
      # E203 - whitespace before ':'
      # E501 - line too long
      # W503 - line break before binary operator
      - --ignore=E126,E203,E501,W503
# run the (very opinionated!) black code formatter - https://github.com/ambv/black
- repo: git://github.com/ambv/black
  rev: 19.3b0
  hooks:
    - id: black
      args:
        - --line-length=120
        - --safe
