version: 2

jobs:
  test:
    docker:
      - image: python:3.7.3-slim-stretch
    steps:
      - run:
          name: Install system dependencies
          command: apt-get update && apt-get install -y gcc libssl-dev
      - checkout
      - run:
          name: Installing Python dependencies
          command: pip install .[test] --progress-bar off
      - run:
          name: Provide an .env:ironment
          command: base64 -d <<< "$PLAYGROUND_ENV" > .env
      - run:
          name: Run tests
          command: pytest -v

workflows:
  version: 2
  test:
    jobs:
      - test
